
import '@/styles/global.scss'
import { Prompt } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const prompt = Prompt({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Medica Clinic',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
